### ISSUE TITLE
AuthError

### ISSUE THREAD

**Issue by ibrarHussain87** [umamakhalid/EasyPaisaExampleAndroidApp#1]
Dear @umamakhalid getting [AuthError](https://easypaystg.easypaisa.com.pk/easypay/faces/pg/site/AuthError.jsf) please suggest something

**Comment by umamakhalid** [comment]
Dear @ibrarHussain87 please be specific. When are you getting this error? What have you tried?

**Comment by ibrarHussain87** [comment]
Dear @umamakhalid thanks for your reply. I used the latest documentation provided by EasyPaisa for integration now they are using an API for payment and integrate successfully.

**Comment by umamakhalid** [comment]
okay.
